---
title: "Chapter 1 - Clique Percolation"
author: "Brooks Ambrose"
date: "October 18, 2015"
output:
  html_document:
    highlight: textmate
    number_sections: yes
    toc: yes
csl: asa.csl
bibliography: d2016.bib
---

```{r init,echo=FALSE}
cat('\014')
rm(list=ls())
source('d2016-init.R')


knitr::opts_chunk$set(error=T,eval=FALSE,fig.path='Figs/ch1') #local defaults
c.f.s.o.def=TRUE
```


```{r dbl2bel-f}
load(paste(out$wok0099,'fuzzy-sets.RData',sep=.Platform$file.sep))
dbl2bel<-dbl2bel.f(
	wok2dbl
	,out=out$wok0041
	,check.for.saved.output=c.f.s.o.def
	,saved_recode=fuzzy.sets
	)
dbl2bel
```

```{r bel2mel-f}
dbl2bel<-dbl2bel[!(zpend|zdup|zloop),list(ut,zcr)]
bel2mel<-bel2mel.f(
	dbl2bel
	,out=out$wok0041
	,check.for.saved.output=c.f.s.o.def
	,type='crel'
	,write2disk=F
)
bel2mel
```

```{r mel2comps-f,include=FALSE}
mel2comps<-mel2comps.f(bel2mel,out=out$wok0041)
```

```{r comps2cos-f}
invisible(comps2cos.f(
	mel2comps.dir=paste(out$wok0041,'mel2comps',sep=.Platform$file.sep)
	,cosparallel.path='~/cosparallel-code/cos'
	,threads=3
	))
```

```{r cos2kcliqdb-f}
cos<-cos2kcliqdb.f(
	mel2comps.dir=paste(out$wok0041,'mel2comps',sep=.Platform$file.sep)
	,out=out$wok0041
	)
```

```{r kcliqdb2flat.f}
cliqdb2flat.f<-function(kcliqdb,type=c('utel','crel')){
	require(data.table)
	ret<-list()
for(i in type)	if(i%in%names(kcliqdb)) {
	ret[[i]]<-data.table(id=unique(unlist(kcliqdb[[i]]$orig)),vlo=0,hlo=0,key='id')
	ret[[i]][,vlo:=table(unlist(lapply(kcliqdb[[i]]$orig,function(x) unique(unlist(x)))))]
	for(j in names(kcliqdb[[i]]$orig)) {
		t<-table(unlist(kcliqdb[[i]]$orig[[j]]))
		ret[[i]][list(as.integer(names(t))),hlo:=hlo+t]
	}
	ret[[i]][,hlo:=hlo-vlo]
	ret[[i]][,tlo:=table(unlist(kcliqdb[[i]]$orig))]
}
	ret
}
cliqdb2flat<-cliqdb2flat.f(cos)
```

```{r kcliqdb2viz-f,eval=FALSE}
kcliqdb2viz.f(cos,paste(out$wok0041,'mel2comps',sep=.Platform$file.sep),out=out$wok0041)
```

```{r unorganized, eval=F}
hulls1<-list()
for(i in unique(unlist(gut4_1$crel$ut))) hulls1[[i]]<-which(V(gut4_1g)$name%in%sort(unique(unlist(gut4_1$crel[sapply(gut4_1$crel$ut,function(x) i%in%x),list(cr1,cr2)]))))

pdf('out/mel/test/1/gut4_1.pdf')
plot(graph.adjacency(sapply(hulls1,function(x) sapply(hulls1,function(y) length(intersect(x,y)))),mode='upper',diag=F,weighted=T))
dev.off()

samp1<-c('WOS:000204992100005','WOS:000205009200002')
pdf('out/mel/test/1/gut4_1g-zcr.pdf')
plot(
	gut4_1g
	,mark.groups=hulls1[samp1]
	,vertex.label=1:length(V(gut4_1g))
	,vertex.size=5
	,vertex.label.cex=.5
	,edge.color=gray(0,.1)
	,vertex.color=c('white','gray')[(1:length(V(gut4_1g))%in%unique(unlist(hulls1[samp1])))+1]
)
dev.off()
write.table(matrix(as.integer(factor(get.edgelist(gut4_1g))),ncol=2),file='out/mel/test/1/1.txt',sep='\t',quote=F,na='',row.names=F,col.names=F)

gut4_2g<-graph.edgelist(as.matrix(gut4_2$crel[,list(as.character(cr1),as.character(cr2))],ncol=2),F)
g<-decompose.graph(gut4_2g)
sg<-sapply(g,vcount)
table(sg)
gut4_2g<-g[[which(sg==max(sg))]]

hulls2<-list()
for(i in unique(unlist(gut4_2$crel$ut))) hulls2[[i]]<-which(V(gut4_2g)$name%in%sort(unique(unlist(gut4_2$crel[sapply(gut4_2$crel$ut,function(x) i%in%x),list(cr1,cr2)]))))

pdf('out/mel/test/2/gut4_2.pdf')
plot(graph.adjacency(sapply(hulls2,function(x) sapply(hulls2,function(y) length(intersect(x,y)))),mode='upper',diag=F,weighted=T))
dev.off()

samp2<-c('WOS:000204682200001','WOS:000204694300003','WOS:000204681700001')
pdf('out/mel/test/2/gut4_2g-zcr.pdf')
plot(
	gut4_2g
	,mark.groups=hulls2[samp2]
	,vertex.label=1:length(V(gut4_2g))
	,vertex.size=5
	,vertex.label.cex=.5
	,edge.color=gray(0,.1)
	,vertex.color=c('white','gray')[(1:length(V(gut4_2g))%in%unique(unlist(hulls2[samp2])))+1]
)
dev.off()
write.table(matrix(as.integer(factor(get.edgelist(gut4_2g))),ncol=2),file='out/mel/test/2/2.txt',sep='\t',quote=F,na='',row.names=F,col.names=F)
```

```{r plot_cosresults, eval=F}
lout<-layout.auto(gut4_1g,repulserad=(vcount(gut4_1g)^3))
pdf('out/mel/test/gut4_1g-zcr-cos.pdf')
mxcol<-max(as.integer(sub('k([0-9]+).*','\\1',names(cos$orig))))
lapply(names(cos$orig),function(j){
	cols<-as.integer(sub('k([0-9]+).*','\\1',names(cos$orig[[j]])))-2
	try(
		plot(
			gut4_1g
			,mark.groups=lapply(cos$orig[[j]],function(i) which(V(gut4_1g)$name%in%levels(cos)[i]))
			,mark.expand=0
			,mark.col=rainbow(mxcol,start=.7,end=.1,alpha=.3)[cols]
			,mark.border=rainbow(mxcol,start=.7,end=.1,alpha=1)[cols]	,vertex.label=1:length(V(gut4_1g))
			,vertex.size=5
			,vertex.label.cex=.5
			,edge.color=gray(0,.1)
			#,vertex.color=c('white','gray')[(1:length(V(gut4_1g))%in%unique(unlist(hulls1[samp1])))+1]
			,main=j
			,layout=lout
		)
	)
})
dev.off()
pdf('out/mel/test/gut4_1g-zcr-cos-strict.pdf')
cols<-as.integer(sub('k([0-9]+).*','\\1',names(cos$strict)))-2
mark.col<-rainbow(max(cols),start=.7,end=.1,alpha=1)[cols] #sapply(1:(max(cols))/max(cols),gray)[cols] #
mark.border<-rainbow(max(cols),start=.7,end=.1,alpha=.3)[cols] #sapply(1:(max(cols))/max(cols),gray)[cols] #
plot(
	gut4_1g
	,mark.groups=lapply(cos$strict,function(i) which(V(gut4_1g)$name%in%levels(cos)[i]))
	,mark.expand=5
	,mark.col=mark.col
	,mark.border=mark.border
	,vertex.label=1:length(V(gut4_1g))
	,vertex.size=5
	,vertex.label.cex=.5
	,edge.color=gray(0,.1)
	#,vertex.color=c('white','gray')[(1:length(V(gut4_1g))%in%unique(unlist(hulls1[samp1])))+1]
	,main="Strict"
	,layout=lout
)
dev.off()
pdf('out/mel/test/gut4_1g-zcr-cos-strict.pdf')
cols<-as.integer(sub('k([0-9]+).*','\\1',names(cos$strict)))-2
mark.col<-terrain.colors(max(cols))[cols] #rainbow(max(cols),start=.7,end=.1,alpha=1)[cols] #sapply(1:(max(cols))/max(cols),gray)[cols] #
mark.border<-mark.col #rainbow(max(cols),start=.7,end=.1,alpha=.3)[cols] #sapply(1:(max(cols))/max(cols),gray)[cols] #
plot(
	gut4_1g
	,mark.groups=lapply(cos$strict,function(i) which(V(gut4_1g)$name%in%levels(cos)[i]))
	,mark.expand=5
	,mark.col=mark.col
	,mark.border=mark.border
	,vertex.label=1:length(V(gut4_1g))
	,vertex.size=5
	,vertex.label.cex=.5
	,edge.color=gray(0,.1)
	#,vertex.color=c('white','gray')[(1:length(V(gut4_1g))%in%unique(unlist(hulls1[samp1])))+1]
	,main="Strict"
	,layout=lout
)
dev.off()
```

```{r 3d-test, eval=F}
z<-do.call(rbind,mapply(function(k,c,l) cbind(k,c,l),k=as.integer(sub('k([0-9]+).*','\\1',names(cos$strict))),c=as.integer(factor(names(cos$strict))),l=cos$strict))
V(gut4_1g)$maxc<-z[order(sapply(z[,'l'],function(i) which(V(gut4_1g)$name%in%levels(cos)[i]))),'c']
V(gut4_1g)$maxk<-z[order(sapply(z[,'l'],function(i) which(V(gut4_1g)$name%in%levels(cos)[i]))),'k']
if(F) {rglplot(
	gut4_1g
	#,mark.groups=lapply(cos$strict,function(i) which(V(gut4_1g)$name%in%levels(cos)[i]))
	#,mark.expand=5
	#,mark.col=mark.col
	#,mark.border=mark.border
	,vertex.label=1:length(V(gut4_1g))
	,vertex.size=5
	,vertex.color=terrain.colors(max(cols))[V(gut4_1g)$maxk-2]
	,vertex.label.cex=.5
	,edge.color=gray(0,.1)
	#,vertex.color=c('white','gray')[(1:length(V(gut4_1g))%in%unique(unlist(hulls1[samp1])))+1]
	,main="Strict"
	,layout=cbind(lout,V(gut4_1g)$maxk)
)}
chulls<-lapply(lapply(split(lout,f=V(gut4_1g)$maxc),matrix,ncol=2),function(x) convex.hull(x)$rescoords)
chulls<-mapply(function(a,b) cbind(a,b[1]),a=chulls,b=split(V(gut4_1g)$maxk,f=V(gut4_1g)$maxc))
open3d()
#rgl.open()
#rgl.bg(color="gray")
#rgl.light()
tercol<-sapply(chulls,function(x) terrain.colors(max(cols))[x[1,3]-2])
for(i in 1:(length(chulls)-1)) {cat(i,"");try(shade3d(extrude3d(chulls[[i]][,-3],thickness=unique(chulls[[i]][,3]),smooth=T),col=tercol[i]))}
movie3d(spin3d(axis=c(0,0,1), rpm=2), duration=30)
#rgl.close()

### original 
cos$origi<-lapply(cos$orig,function(x) sapply(x,function(i) which(V(gut4_1g)$name%in%levels(cos)[i])))
cos$stricti<-lapply(cos$strict,function(x) sapply(x,function(i) which(V(gut4_1g)$name%in%levels(cos)[i])))
for(i in 1:(length(cos$stricti))) {cat(i,"");try(shade3d(extrude3d(lout[cos$stricti,],thickness=unique(chulls[[i]][,3]),smooth=T),col=tercol[i]))}

resize.Polygon <- function(coords, size=1.0) {
	tmp <- scale(coords[,], scale=rep(1/size, 2))
	scaled <- t(tmp) + attr(tmp, 'scaled:center')
	closed <- t(cbind(scaled, scaled[,1]))
	closed
}

ks<-as.integer(sub('k([0-9]+).*','\\1',names(cos$origi)))
cs<-terrain.colors(max(ks))[ks]
open3d()
mapply(function(memb,k,clr,scl) try(shade3d(extrude3d(
	resize.Polygon(convex.hull(lout[memb,])$rescoords,size=scl),smooth=T,thickness=k),col=clr)),memb=cos$origi,k=ks,clr=cs,scl=1-(as.integer(factor(ks))-1)/1000)
play3d(spin3d(axis=c(0,0,1), rpm=2), duration=30)

```